[pytest]
testpaths =
    SuperBirdUpdater/tests
    build_tools/tests
    app_common/tests
    bird_sharpness/tests
    image_denoise/tests
    SuperViewer/tests
    SuperBirdStamp/tests
pythonpath =
    .
    SuperBirdStamp
