from app_common.image_formats import (
    HEIF_IMAGE_EXTENSIONS,
    PIL_IMAGE_EXTENSIONS,
    PHOTOSHOP_IMAGE_EXTENSIONS,
    RAW_IMAGE_EXTENSIONS,
    STANDARD_IMAGE_EXTENSIONS,
    SUPPORTED_IMAGE_EXTENSIONS,
)

STANDARD_EXTENSIONS = STANDARD_IMAGE_EXTENSIONS
HEIF_EXTENSIONS = HEIF_IMAGE_EXTENSIONS
RAW_EXTENSIONS = RAW_IMAGE_EXTENSIONS
PHOTOSHOP_EXTENSIONS = PHOTOSHOP_IMAGE_EXTENSIONS
PIL_EXTENSIONS = PIL_IMAGE_EXTENSIONS
SUPPORTED_EXTENSIONS = SUPPORTED_IMAGE_EXTENSIONS

DEFAULT_SHOW_FIELDS = {
    "bird",
    "time",
    "location",
    "gps",
    "camera",
    "lens",
    "settings",
}

VALID_MODES = {"keep", "fit", "square", "vertical"}
VALID_FRAME_STYLES = {"crop", "pad"}

# 单例 IPC 用：接收「发送到本应用」文件列表时的服务名
SEND_TO_APP_ID = "birdstamp"

